FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80


# FROM python:3.11-slim
# WORKDIR /app
# COPY app.py /app
# RUN pip install flask
# EXPOSE 80
# CMD ["python", "app.py"]
